version: "3.7"
services:
  
  db_1:
    image: postgres:13-alpine
    container_name: pgdb_1
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres_1
      POSTGRES_DB: messages
      TZ: 'Asia/Novosibirsk'
      PGTZ: 'Asia/Novosibirsk'
    volumes:
      - ./pgdata:/var/lib/postgresl/data
    ports: 
      - "5431:5432"
      
  db_2:
    image: postgres:13-alpine
    container_name: pgdb_2
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres_2
      POSTGRES_DB: messages
      TZ: 'Asia/Novosibirsk'
      PGTZ: 'Asia/Novosibirsk'
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports: 
      - "5432:5432"

  nats:
    image: nats:latest
    container_name: nats_server
    restart: on-failure
    depends_on:
      - db_1
      - db_2
    ports: 
      - "4222:4222"

  message_node_1:
    build: ./service_1/
    container_name: service_1
    restart: on-failure
    depends_on:
      - nats
      - db_1
    links:
      - "db_1"
      - "nats"

  message_node_2:
    build: ./service_2/
    container_name: service_2
    restart: on-failure
    depends_on:
      - nats
      - db_2
    links:
      - "db_2"
      - "nats"
     